Update workflow

diff --git a/.github/workflows/publish-report/action.yml b/.github/workflows/publish-report/action.yml
--- a/.github/workflows/publish-report/action.yml
+++ b/.github/workflows/publish-report/action.yml
@@ -2,68 +2,74 @@ name: Publish test report artifact to GH Pages
 
 on: workflow_call
 
-jobs:
-  publish:
-    runs-on: ubuntu-latest
-    if: "success() || needs.test.result == 'failure'"
-    needs: [test]
+# jobs:
+#   publish:
+#     runs-on: ubuntu-latest
+#     if: "success() || needs.test.result == 'failure'"
+#     needs: [test]
 
-    env:
-      # Unique URL path for each workflow run attempt
-      HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
+runs:
+  using: "composite"
 
-    steps:
-      - name: Checkout GitHub Pages Branch
-        uses: actions/checkout@v3
-        with:
-          ref: gh-pages
+  env:
+    # Unique URL path for each workflow run attempt
+    HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
 
-      - name: Set Git User
-        # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
-        run: |
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+  steps:
+    - name: Checkout GitHub Pages Branch
+      uses: actions/checkout@v3
+      with:
+        ref: gh-pages
 
-      - name: Download zipped HTML report
-        uses: actions/download-artifact@v2
-        with:
-          name: playwright-report
-          path: ${{ env.HTML_REPORT_URL_PATH }}
+    - name: Set Git User
+      shell: bash
+      # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
+      run: |
+        git config --global user.name "github-actions[bot]"
+        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
-      - name: Push HTML Report
-        timeout-minutes: 3
-        # commit report, then try push-rebase-loop until it's able to merge the HTML report to the gh-pages branch
-        # this is necessary when this job running at least twice at the same time (e.g. through two pushes at the same time)
-        run: |
-          git add .
-          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
+    - name: Download zipped HTML report
+      uses: actions/download-artifact@v2
+      with:
+        name: playwright-report
+        path: ${{ env.HTML_REPORT_URL_PATH }}
 
-          while true; do
-            git pull --rebase
-            if [ $? -ne 0 ]; then
-              echo "Failed to rebase. Please review manually."
-              exit 1
-            fi
+    - name: Push HTML Report
+      timeout-minutes: 3
+      shell: bash
+      # commit report, then try push-rebase-loop until it's able to merge the HTML report to the gh-pages branch
+      # this is necessary when this job running at least twice at the same time (e.g. through two pushes at the same time)
+      run: |
+        git add .
+        git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
 
-            git push
-            if [ $? -eq 0 ]; then
-              echo "Successfully pushed HTML report to repo."
-              exit 0
-            fi
-          done
+        while true; do
+          git pull --rebase
+          if [ $? -ne 0 ]; then
+            echo "Failed to rebase. Please review manually."
+            exit 1
+          fi
 
-      - name: Output Report URL as Worfklow Annotation
-        run: |
-          FULL_HTML_REPORT_URL=https://internetarchive.github.io/archiveorg-e2e-playwright/$HTML_REPORT_URL_PATH
+          git push
+          if [ $? -eq 0 ]; then
+            echo "Successfully pushed HTML report to repo."
+            exit 0
+          fi
+        done
 
-          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
+    - name: Output Report URL as Worfklow Annotation
+      shell: bash
+      run: |
+        FULL_HTML_REPORT_URL=https://internetarchive.github.io/archiveorg-e2e-playwright/$HTML_REPORT_URL_PATH
 
-      - name: Publish notifications to slack channel
-        uses: act10ns/slack@v2
-        with:
-          status: ${{ job.status }}
-          steps: ${{ toJson(steps) }}
-          channel: '#git-e2e-tests'
-          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
-          message: "Playwright report page - https://internetarchive.github.io/archiveorg-e2e-playwright/${{ env.HTML_REPORT_URL_PATH }}"
-        if: always()
+        echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
+
+    - name: Publish notifications to slack channel
+      uses: act10ns/slack@v2
+      with:
+        status: ${{ job.status }}
+        steps: ${{ toJson(steps) }}
+        channel: '#git-e2e-tests'
+        webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
+        message: "Playwright report page - https://internetarchive.github.io/archiveorg-e2e-playwright/${{ env.HTML_REPORT_URL_PATH }}"
+      if: always()
