Change workflow 01

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,6 +18,7 @@ jobs:
   #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
 
   test:
+    name: Run tests
     uses: ./.github/workflows/call-run-tests.yml
 
   publish_report:
@@ -33,22 +34,59 @@ jobs:
       REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
     
     steps:
-      - uses: actions/checkout@v3
-
-      - name: Publish GH Pages
-        uses: ./.github/workflows/call-publish-ghpages.yml
+      - name: Checkout GitHub Pages Branch
+        uses: actions/checkout@v3
         with:
-          repoURL: ${{ env.REPO_URL }}
-          reportURL: ${{ env.REPORT_URL }}
+          ref: gh-pages
 
-      - name: Publish notifications to slack channel
-        uses: act10ns/slack@v2
+      - name: Set Git User
+        # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
+      - name: Download zipped HTML report
+        uses: actions/download-artifact@v2
         with:
-          status: ${{ job.status }}
-          steps: ${{ toJson(steps) }}
-          channel: '#git-e2e-tests'
-          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
-          message: Playwright report page - https://${{ env.REPO_URL }}/${{ env.HTML_REPORT_URL_PATH }}
-        if: always()
+          name: playwright-report
+          path: ${{ inputs.reportURL }}
+
+      - name: Push HTML Report
+        timeout-minutes: 3
+        # commit report, then try push-rebase-loop until it's able to merge the HTML report to the gh-pages branch
+        # this is necessary when this job running at least twice at the same time (e.g. through two pushes at the same time)
+        run: |
+          git add .
+          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
+
+          while true; do
+            git pull --rebase
+            if [ $? -ne 0 ]; then
+              echo "Failed to rebase. Please review manually."
+              exit 1
+            fi
+
+            git push
+            if [ $? -eq 0 ]; then
+              echo "Successfully pushed HTML report to repo."
+              exit 0
+            fi
+          done
+
+      - name: Output Report URL as Worfklow Annotation
+        run: |
+          FULL_HTML_REPORT_URL=https://${{ env.REPO_URL }}/${{ env.REPORT_URL_PATH }}
+
+          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
+
+      # - name: Publish notifications to slack channel
+      #   uses: act10ns/slack@v2
+      #   with:
+      #     status: ${{ job.status }}
+      #     steps: ${{ toJson(steps) }}
+      #     channel: '#git-e2e-tests'
+      #     webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
+      #     message: Playwright report page - https://${{ env.REPO_URL }}/${{ env.HTML_REPORT_URL_PATH }}
+      #   if: always()
 
 
