Update github workflows

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -7,32 +7,14 @@ on:
 jobs:
   notify:
     # run slack-notifier workflow
-    uses: ./.github/workflows/slack-notifier.yml
+    uses: ./.github/workflows/call-slack-notifier.yml
     with:
       message: Starting push to main branch playwright tests run...
     secrets:
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
 
   test:
-    timeout-minutes: 60
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v3
-    - uses: actions/setup-node@v3
-      with:
-        node-version: 16
-    - name: Install dependencies
-      run: npm ci
-    - name: Install Playwright Browsers
-      run: npx playwright install --with-deps
-    - name: Run Playwright tests
-      run: npx playwright test
-    - uses: actions/upload-artifact@v3
-      if: always()
-      with:
-        name: playwright-report
-        path: playwright-report/
-        retention-days: 30
+    uses: ./.github/workflows/run-tests.yml
 
   publish_report:
     name: Publish HTML Report
@@ -45,52 +27,51 @@ jobs:
       # Unique URL path for each workflow run attempt
       HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
     steps:
-      - name: Checkout GitHub Pages Branch
-        uses: actions/checkout@v2
-        with:
-          ref: gh-pages
-      - name: Set Git User
-        # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
-        run: |
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
-      - name: Download zipped HTML report
-        uses: actions/download-artifact@v2
-        with:
-          name: playwright-report
-          path: ${{ env.HTML_REPORT_URL_PATH }}
-      - name: Push HTML Report
-        timeout-minutes: 3
-        # commit report, then try push-rebase-loop until it's able to merge the HTML report to the gh-pages branch
-        # this is necessary when this job running at least twice at the same time (e.g. through two pushes at the same time)
-        run: |
-          git add .
-          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
+      - uses: ./.github/workflows/call-publish-report.yml
+      #   with:
+      #     ref: gh-pages
+      # - name: Set Git User
+      #   # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
+      #   run: |
+      #     git config --global user.name "github-actions[bot]"
+      #     git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+      # - name: Download zipped HTML report
+      #   uses: actions/download-artifact@v2
+      #   with:
+      #     name: playwright-report
+      #     path: ${{ env.HTML_REPORT_URL_PATH }}
+      # - name: Push HTML Report
+      #   timeout-minutes: 3
+      #   # commit report, then try push-rebase-loop until it's able to merge the HTML report to the gh-pages branch
+      #   # this is necessary when this job running at least twice at the same time (e.g. through two pushes at the same time)
+      #   run: |
+      #     git add .
+      #     git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
 
-          while true; do
-            git pull --rebase
-            if [ $? -ne 0 ]; then
-              echo "Failed to rebase. Please review manually."
-              exit 1
-            fi
+      #     while true; do
+      #       git pull --rebase
+      #       if [ $? -ne 0 ]; then
+      #         echo "Failed to rebase. Please review manually."
+      #         exit 1
+      #       fi
 
-            git push
-            if [ $? -eq 0 ]; then
-              echo "Successfully pushed HTML report to repo."
-              exit 0
-            fi
-          done
-      - name: Output Report URL as Worfklow Annotation
-        run: |
-          FULL_HTML_REPORT_URL=https://internetarchive.github.io/archiveorg-e2e-playwright/$HTML_REPORT_URL_PATH
+      #       git push
+      #       if [ $? -eq 0 ]; then
+      #         echo "Successfully pushed HTML report to repo."
+      #         exit 0
+      #       fi
+      #     done
+      # - name: Output Report URL as Worfklow Annotation
+      #   run: |
+      #     FULL_HTML_REPORT_URL=https://internetarchive.github.io/archiveorg-e2e-playwright/$HTML_REPORT_URL_PATH
 
-          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
-      - name: Publish notifications to slack channel
-        uses: act10ns/slack@v2
-        with:
-          status: ${{ job.status }}
-          steps: ${{ toJson(steps) }}
-          channel: '#git-e2e-tests'
-          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
-          message: Playwright report page - https://internetarchive.github.io/archiveorg-e2e-playwright/$HTML_REPORT_URL_PATH
-        if: always()
+      #     echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
+      # - name: Publish notifications to slack channel
+      #   uses: act10ns/slack@v2
+      #   with:
+      #     status: ${{ job.status }}
+      #     steps: ${{ toJson(steps) }}
+      #     channel: '#git-e2e-tests'
+      #     webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
+      #     message: Playwright report page - https://internetarchive.github.io/archiveorg-e2e-playwright/$HTML_REPORT_URL_PATH
+      #   if: always()
